title: "RoboChef"
description: "We are building robot"
url: https://roboticchef.github.io
baseurl: ""

remote_theme: riggraz/no-style-please

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

theme_config:
  appearance: auto
  show_description: true

img: "assets/images"
